### ISSUE TITLE
Feature request: Map Lagoon API projects to Ansible inventory projects

### ISSUE THREAD

**Issue by GROwen** [salsadigitalauorg/lagoon_ansible_collection#10]
### Use case
When limiting a run of a playbook I can use Lagoon groups to identify the hosts.

We have multiple projects that are conceptually grouped based on arbitrary values. We're in need of a way to limit the list of hosts to these projects, and groups, both Lagoon and Ansible, would be the ideal way to do this.

This will need a method to map the Lagoon group to an Ansible Inventory group.

### Acceptance Criteria
1. Setting the parameter `--limit lagoon_group_name` limits the list of hosts to projects with that Lagoon group

**Comment by yusufhm** [comment]
Done as part of #14
